search_url = ""

authors = []

result_selector = "a[href=\"/g/\"]"
title_selector  = ""
link_selector   = ""

[telegram]
enabled   = true
bot_token = "YOUR_TELEGRAM_BOT_TOKEN"
chat_id   = "YOUR_TELEGRAM_CHAT_ID"
